In [1]:
import numpy as np
import pandas as pd

# Pandas 자료 구조 소개

## Series

In [2]:
obj = pd.Series([4,7,5,-3])

In [3]:
obj

0    4
1    7
2    5
3   -3
dtype: int64

In [5]:
obj.values

array([ 4,  7,  5, -3], dtype=int64)

In [6]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [15]:
obj2 = pd.Series([4,7,-5,3], index = ['d','b','a','c'])

In [16]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [17]:
obj2[['b','c']]

b    7
c    3
dtype: int64

In [18]:
obj2['d'] = 6

In [20]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [21]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [23]:
obj2.isin([6])

d     True
b    False
a    False
c    False
dtype: bool

In [24]:
'b' in obj2

True

In [25]:
sdata = {'Ohio' : 35000, 'Texas':71000, 'Oregon':16000, 'Utah':5000}

In [26]:
obj3 = pd.Series(sdata)

In [27]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [28]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [29]:
obs4 = pd.Series(sdata, index = states)

In [30]:
obs4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [31]:
pd.isnull(obs4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [32]:
obj3 + obs4 ## join 연산과 유사함

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [33]:
obs4.name = 'population'

In [34]:
obs4.index.name = 'state'

In [35]:
obs4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

## DataFrame

In [36]:
data = {'state' : ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
       'year':[2000,2001,2002,2000,2001,2002],
       'pop':[1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [37]:
df = pd.DataFrame(data)

In [38]:
df

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2000  2.4
4  Nevada  2001  2.9
5  Nevada  2002  3.2

In [39]:
df.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2000  2.4
4  Nevada  2001  2.9

In [41]:
pd.DataFrame(data, columns = ['year', 'state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2000  Nevada  2.4
4  2001  Nevada  2.9
5  2002  Nevada  3.2

In [42]:
df2 = pd.DataFrame(data, columns = ['year', 'state','pop','debt'],
                  index = ['one','two','three','four','five','six'])

In [43]:
df2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2000  Nevada  2.4  NaN
five   2001  Nevada  2.9  NaN
six    2002  Nevada  3.2  NaN

In [47]:
df2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [49]:
df2['debt'] = 16.5

In [50]:
df2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2000  Nevada  2.4  16.5
five   2001  Nevada  2.9  16.5
six    2002  Nevada  3.2  16.5

In [52]:
df2['debt'] = np.arange(6.)

In [53]:
df2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2000  Nevada  2.4   3.0
five   2001  Nevada  2.9   4.0
six    2002  Nevada  3.2   5.0

In [54]:
val = pd.Series([-1.2, -1.5, -1.7], index = ['two', 'four', 'five'])

In [56]:
df2['debt'] = val

In [58]:
df2.head()

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2000  Nevada  2.4  -1.5
five   2001  Nevada  2.9  -1.7

In [60]:
df2['eastern'] = df2.state == 'Ohio'

In [61]:
df2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2000  Nevada  2.4  -1.5    False
five   2001  Nevada  2.9  -1.7    False
six    2002  Nevada  3.2   NaN    False

In [62]:
del df2['eastern']

In [63]:
df2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2000  Nevada  2.4  -1.5
five   2001  Nevada  2.9  -1.7
six    2002  Nevada  3.2   NaN

In [9]:
pop = {'Nevada':{2001:2.4, 2002:2.9}, 'Ohio':{2000:1.5,2001:1.7,2002:3.6}}

In [10]:
df3 = pd.DataFrame(pop)

In [11]:
df3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [67]:
df3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [68]:
pd.DataFrame(pop, index = [2001,2002,2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [13]:
df3.index.name = 'year'; df3.columns.name = 'state'

In [70]:
df3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [72]:
df3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [73]:
df2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2000, 'Nevada', 2.4, -1.5],
       [2001, 'Nevada', 2.9, -1.7],
       [2002, 'Nevada', 3.2, nan]], dtype=object)

## 색인객체

In [3]:
obj = pd.Series(range(3), index = ['a','b','c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [5]:
labels = pd.Index(np.arange(3))

In [6]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [7]:
obj2= pd.Series([0.5, -2.5, 0], index = labels)

In [8]:
obj2

0    0.5
1   -2.5
2    0.0
dtype: float64

In [15]:
df3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

# 핵심 기능

## 재색인
* 새로운 색인에 맞도록 객체를 새로 생성

In [16]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index = ['d','b','a','c'])

In [17]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [18]:
obj2 = obj.reindex(['a','b','c','d','e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [19]:
obj3 = pd.Series(['blue','purple','yellow'], index = [0,2,4])

In [20]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [22]:
obj3.reindex(range(6), method = 'ffill') ## 누락된 값을 직전의 값으로 채움.

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [23]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)),
                    index = ['a','c','d'],
                    columns = ['Ohio', 'Texas','California'])

In [24]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [25]:
frame2 = frame.reindex(['a','b','c','d'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [26]:
states =['Texas', 'Utah', 'California']
frame.reindex(columns = states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

* 재색인 함수 인자
  - index : 색인으로 사용할 새로운 순서
  - method : 채움 메서드, ffill 은 직전 값을 채워넣고, bfill은 다음 값을 채워넣는다
  - fill_vaule : 재색인 과정 중에 새롭게 나타나는 비어있는 데이터를 채우기 위한 값
  - limit : 전후 보간 시 사용할 최대 갭 크기(채워넣을 원소의 수)
  - tolerance : 전후 보간 시 사용할 최대 갭 크기(값차이)
  - level : Multiindex의 단계에 단순 색인을 맞춤.
  - copy : True 인 경우 새로운 색인이 이전 색인과 동일하더라도 데이터를 복사

## 하나의 로우나 컬럼 삭제하기

In [2]:
obj = pd.Series(np.arange(5.), index = ['a','b','c','d','e'])

In [3]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [5]:
new_obj = obj.drop('c')

In [6]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [7]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),
                   index = ['Ohio','Colorado','Utah','New York'],
                   columns = ['one','two','three','four'])

In [8]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [10]:
data.drop(['Colorado','Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [12]:
data.drop(['two','three'], axis = 'columns')

one  four
Ohio        0     3
Colorado    4     7
Utah        8    11
New York   12    15

## 색인하기, 선택하기, 거르기

In [13]:
obj = pd.Series(np.arange(4.), index = ['a','b','c','d'])

In [14]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [15]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [16]:
obj[['b','a']]

b    1.0
a    0.0
dtype: float64

In [17]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [18]:
obj[obj<3]

a    0.0
b    1.0
c    2.0
dtype: float64

In [19]:
obj['b':'c']## 라벨 이름으로 슬라이싱하면 시작점과 끝점을 포함

b    1.0
c    2.0
dtype: float64

In [20]:
data = pd.DataFrame(np.arange(16).reshape((4,4)), 
                   index = ['Ohio','Colorado','Utah','New York'],
                   columns = ['one','two','three','four'])

In [21]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [23]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [24]:
data[['three','one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [25]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [26]:
data[data['three']>5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

### loc나 iloc로 선택하기

In [27]:
data.loc['Colorado',['two','three']]

two      5
three    6
Name: Colorado, dtype: int32

In [28]:
data.iloc[2, [3,0,1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [29]:
data.iloc[[1,2],[3,0,1]]

four  one  two
Colorado     7    4    5
Utah        11    8    9

In [30]:
data.loc[:'Utah','two']

Ohio        1
Colorado    5
Utah        9
Name: two, dtype: int32

In [32]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    4    5      6
Utah        8    9     10
New York   12   13     14

In [41]:
data[data.three > 5][["one","two","three"]]

one  two  three
Colorado    4    5      6
Utah        8    9     10
New York   12   13     14

## 정수 색인

In [42]:
ser = pd.Series(np.arange(3.))

In [44]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [47]:
ser[-1] 
## 라벨 색인이 0,1,2를 포함하는 경우 사용자가 라벨 색인으로 선택하려는 것인지, 
# 정수 색인으로 선택하려는 것인지 추측하기 쉽지 않다.

KeyError: -1

In [45]:
ser2 = pd.Series(np.arange(3.), index = ['a','b','c'])

In [46]:
ser2[-1]

2.0

In [48]:
ser[:1] ## 일관성을 유지하기 위해 정수값을 담고 있는 축 색인이 있다면 우선적으로 라벨을 먼저 찾아보도록 구현되어 있다.

0    0.0
dtype: float64

* 라벨에 대해서는 loc를 사용하고, 정수 색인에 대해서는 iloc를 사용하자

In [49]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [50]:
ser.iloc[:1]

0    0.0
dtype: float64

## 산술연산과 데이터 정렬

In [51]:
s1 = pd.Series([7.3, -2.5,3.4,1.5], index = ['a','c','d','e'])
s2 = pd.Series([-2.1, 3.6,-1.5,4,3.1], index = ['a','c','e','f','g'])

In [52]:
s1 + s2 ## 서로 겹치는 색인이 없는 경우 데이터는 NA값이 된다.

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [53]:
df1 = pd.DataFrame(np.arange(9.).reshape((3,3)), columns = list('bcd'), index = ['Ohio', 'Texas', 'Colorado'])
df2 = pd.DataFrame(np.arange(12.).reshape((4,3)), columns = list('bde'), index = ['Utah','Ohio', 'Texas', 'Oregon'])

In [54]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [55]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [56]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [58]:
df1 = pd.DataFrame(np.arange(12.).reshape((3,4)), columns = list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4,5)), columns = list('abcde'))

In [59]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [60]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [62]:
df1.add(df2, fill_value = 0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [63]:
1/df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [64]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [66]:
1/df1 ==  df1.rdiv(1)

a     b     c     d
0  True  True  True  True
1  True  True  True  True
2  True  True  True  True

In [2]:
arr = np.arange(12.).reshape((3,4))

In [3]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [4]:
arr[0]

array([0., 1., 2., 3.])

In [5]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [6]:
frame = pd.DataFrame(np.arange(12.).reshape((4,3)),
                    columns = list('bde'),
                    index = ['Utah','Ohio','Texas','Oregon'])

In [7]:
series = frame.iloc[0]
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [8]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [13]:
series2 = pd.Series(range(3), index = ['b','e','f'])

In [15]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [16]:
series3 = frame['d']
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [17]:
frame.sub(series3, axis = 0)

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

## 함수 적용과 매핑

In [18]:
frame = pd.DataFrame(np.random.randn(4,3), columns = list('bde'), 
                    index = ['Utah','Ohio','Texas','Oregon'])

In [19]:
frame

b         d         e
Utah   -0.377748  0.590948  0.373759
Ohio    1.240495 -0.250626 -0.007763
Texas   0.777129 -1.232912 -1.824599
Oregon -1.528413 -0.123234  1.706448

In [20]:
frame.abs()

b         d         e
Utah    0.377748  0.590948  0.373759
Ohio    1.240495  0.250626  0.007763
Texas   0.777129  1.232912  1.824599
Oregon  1.528413  0.123234  1.706448

In [21]:
f = lambda x:x.max() - x.min()

In [23]:
frame.apply(f, axis = 'columns')

Utah      0.968696
Ohio      1.491121
Texas     2.601727
Oregon    3.234862
dtype: float64

In [24]:
def f(x) :
    return pd.Series([x.min(), x.max()], index = ['min','max'])

In [25]:
frame.apply(f)

b         d         e
min -1.528413 -1.232912 -1.824599
max  1.240495  0.590948  1.706448

In [26]:
format = lambda x: '%.2f' %x
frame.applymap(format)

b      d      e
Utah    -0.38   0.59   0.37
Ohio     1.24  -0.25  -0.01
Texas    0.78  -1.23  -1.82
Oregon  -1.53  -0.12   1.71

## 정렬과 순위

In [28]:
obj = pd.Series(range(4), index = ['d','a','b','c'])

In [29]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [30]:
frame = pd.DataFrame(np.arange(8).reshape((2,4)),
                    index = ['three', 'one'],
                    columns = ['d','a','b','c'])

In [31]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [33]:
frame.sort_index(axis = 1, ascending = False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [36]:
obj = pd.Series([4,np.nan, 7,-3,np.nan, 2])

In [37]:
obj.sort_values()
## 정렬할 때 비어있는 값은 기본적으로 가장 마지막에 위치

3   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
4    NaN
dtype: float64

In [38]:
frame = pd.DataFrame({'b':[4,7,-3,2], 'a':[0,1,0,1]})

In [39]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [40]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [41]:
frame.sort_values(by=['a','b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [42]:
obj = pd.Series([7,-5,7,4,2,0,4])

In [44]:
obj.rank(method = 'first') ## 데이터 상 나타나는 위치에 따라 순위

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [46]:
obj.rank(method = 'max', ascending = False) 

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

```
'average' : 같은 값을 가지는 항목들의 평균값을 순위로, (디폴트설정)
'min' : 같은 값을 가지는 그룹을 낮은 순위로 매긴다
'max' : 같은 값을 가지는 그룹을 높은 순위로 매긴다.
'first' : 데이터 내의 위치에 따라 순위를 매긴다
'dense' : method = 'min'과 같지만 같은 그룹 내에서 모두 같은 순위를 적용하지 않고 1씩 증가시킨다.
```

## 중복 색인

In [47]:
obj = pd.Series(range(5), index = ['a','a','b','b','c'])

In [48]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [49]:
obj.index.is_unique

False

In [50]:
df = pd.DataFrame(np.random.randn(4,3), index = ['a','a','b','b'])
df

0         1         2
a  0.297606 -1.082772 -0.317438
a  0.243007 -0.293123  2.352819
b -0.334304  0.604595 -1.512456
b -1.404872  2.968775  0.879920

In [51]:
df.loc['b']

0         1         2
b -0.334304  0.604595 -1.512456
b -1.404872  2.968775  0.879920

# 기술 통계와 요약

In [52]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5], [np.nan, np.nan],[0.75, -1.3]],
                 index = list('abcd'), columns = ['one','two'])

In [53]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [58]:
df.mean(axis = 1, skipna = False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [62]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

## 상관관계와 공분산

In [61]:
import pandas_datareader.data as web

In [63]:
all_data = {ticker : web.get_data_yahoo(ticker) for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}
price = pd.DataFrame({ticker:data['Adj Close'] for ticker , data in all_data.items()})
volume = pd.DataFrame({ticker:data['Volume'] for ticker, data in all_data.items()})

In [64]:
returns = price.pct_change()

In [66]:
returns.tail()

AAPL       IBM      MSFT      GOOG
Date                                              
2021-09-21  0.003428 -0.009977  0.001699  0.004528
2021-09-22  0.016872  0.012484  0.012822  0.009252
2021-09-23  0.006719  0.015598  0.003282  0.006301
2021-09-24  0.000613  0.005558 -0.000701  0.005686
2021-09-27 -0.010550  0.007782 -0.017304 -0.007936

In [69]:
price.head()

AAPL         IBM       MSFT        GOOG
Date                                                    
2016-09-28  26.716732  126.382088  53.691029  781.559998
2016-09-29  26.301737  126.238419  53.108139  775.010010
2016-09-30  26.505720  126.829239  53.293175  777.289978
2016-10-03  26.381449  125.839165  53.126625  772.559998
2016-10-04  26.493990  124.921028  52.960094  776.429993

In [70]:
returns['MSFT'].corr(returns['IBM'])

0.5138950668502592

In [71]:
returns.MSFT.corr(returns.IBM)

0.5138950668502592

In [72]:
returns.corr()

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.441827  0.737518  0.664605
IBM   0.441827  1.000000  0.513895  0.482320
MSFT  0.737518  0.513895  1.000000  0.774390
GOOG  0.664605  0.482320  0.774390  1.000000

In [73]:
returns.cov()

AAPL       IBM      MSFT      GOOG
AAPL  0.000361  0.000137  0.000241  0.000213
IBM   0.000137  0.000268  0.000144  0.000133
MSFT  0.000241  0.000144  0.000295  0.000224
GOOG  0.000213  0.000133  0.000224  0.000283

In [75]:
returns.corrwith(returns.IBM)

AAPL    0.441827
IBM     1.000000
MSFT    0.513895
GOOG    0.482320
dtype: float64

In [77]:
returns.corrwith(volume)

AAPL   -0.076809
IBM    -0.103196
MSFT   -0.056907
GOOG   -0.122337
dtype: float64

## 유일값, 값 세기, 멤버십

In [78]:
obj = pd.Series(['c','a','d','a','a','b','b','c','c'])

In [79]:
uniques = obj.unique()

In [80]:
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [81]:
pd.value_counts(obj.values, sort = False)

c    3
d    1
a    3
b    2
dtype: int64

In [82]:
mask = obj.isin(['b','c'])

In [83]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [84]:
to_match = pd.Series(['c','a','b','b','c','a'])

In [85]:
unique_vals = pd.Series(['c','b','a'])

In [87]:
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2], dtype=int64)

In [88]:
## DATAframe 여러 컬럼에 대해 히스토그램을 구해야 하는 경우가 있다.
data = pd.DataFrame({'Qu1':[1,3,4,3,4],
                    'Qu2':[2,3,1,2,3],
                    'Qu3':[1,5,2,4,4]})

In [89]:
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [92]:
result = data.apply(pd.value_counts).fillna(0)

In [93]:
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0